# Generated by Django 5.1.3 on 2024-11-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=25)),
                ('isbn', models.CharField(max_length=14, unique=True)),
                ('genere', models.CharField(max_length=15)),
                ('copies', models.IntegerField()),
            ],
        ),
    ]
